language: python

python:
    - "3.4"
    - "3.5"

virtualenv:
    system_site_packages: true

before_install:
    - ./bootstrap-debian.sh

install:
    - ./install.py
    - ./install.py --uninstall=virtualenv

script:
    - ./install.py --checks --tests
